version: '3.4'

networks:
  local:

services:
  tests:
    image: hseeberger/scala-sbt:8u222_1.3.5_2.12.10
    working_dir: /app
    volumes:
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
      - $PWD:/app
    command: sbt ~test
    networks:
      local:
